//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAronsAmmoShack.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Damages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Damages()
        {
            this.Ammos = new HashSet<Ammos>();
        }
    
        public int DamageID { get; set; }
        public Nullable<decimal> Penetration { get; set; }
        public Nullable<decimal> Damage1 { get; set; }
        public Nullable<decimal> ArmorDamage { get; set; }
        public Nullable<decimal> FragmentationChange { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ammos> Ammos { get; set; }
    }
}
