//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAronsAmmoShack.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedFirearms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RelatedFirearms()
        {
            this.Ammos = new HashSet<Ammos>();
        }
    
        public int RFID { get; set; }
        public string FamilyName { get; set; }
        public string FamilyDescription { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ammos> Ammos { get; set; }
        public virtual Manufacturers Manufacturer { get; set; }
    }
}
